
#blog:
#    title: BankLine API
#    banner:
#        title: BankLine
#        content: The BankLine API will be down tomorrow.

# Spring Boot configuration
spring:
    config:
        activate:
            on-profile: test
    # Security configuration
    security:
        user:
            name: user
            password: user
    # database
    datasource:
        url: jdbc:postgresql://192.168.0.106:54432/bankline_api
#        driverClassName: org.h2.Driver
        driver-class-name: org.postgresql.Driver
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres
    # JPA properties
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
        show-sql: true
#        database: postgresql
        open-in-view: false
        generate-ddl: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true

# Logger configuration
logging:
    pattern:
        console: "%d %-5level %logger : %msg%n"
    level:
        org.springframework: info
        org.hibernate: debug
# Server configuration
server:
    port: 8080 #set your port